version: '3'
services:
  app:
    image: swiftlintbot:latest
    build:
      context: .
    restart: always
    ports:
      - '8080:8080'
    command: "--bitbucket ${BITBUCKET} --secret ${BITBUCKETSECRET} --configuration ${CONFIGURATION}"
